# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46d91ec99b1a12a02391014fd126208d225c80fe5e44b6cc1f0331eacefbd1d0d2e573c4d71bd9e4d0140b87d555cfad267eeece5a3ba754fcc857277fa2a6c

test:
  secret_key_base: fb616c09fbb9496cab9d5a0c21b034c48810e0ec9bee255ffb33627e6586973a52c82cd6ad3ed4c5d87333a4d1f88a1da8bcb008d8cd9accaca86e6a258bbb6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
