export const style = {
  overlay : {
  	display         : 'flex',
  	justifyContent  : 'center',
  	alignItems      : 'center',
    position        : 'fixed',
    top             : 0,
    left            : 0,
    right           : 0,
    bottom          : 0,
    backgroundColor : 'rgba(163, 163, 163, 0.75)',
    paddingBottom   : '10%',
  },
  content : {
  	display					: 'flex',
    flexDirection   : 'column',
  	justifyContent  : 'center',
    position        : 'fixed',
    top             : 'auto',
    left            : 'auto',
    right           : 'auto',
    bottom          : 'auto',
    backgroundColor : 'rgba(43, 143, 209, 1)',
    border          : '1px solid #ccc',
    borderWidth     : '0',
    fontFamily      : 'Roboto',
    padding         : '0',
    paddingBottom   : '30px',
    height          : '40%',
    width           : '40%',
  }
};
